scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
        - prometheus:9090

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:8081

  - job_name: node-exporter
    scrape_interval: 5s
    static_configs:
      - targets:
        - node-exporter:9100

  - job_name: 'Spring Boot Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'SpringBoot Example Exporter'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093

rule_files:
  - 'alert.rules'