route:
  receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
    - send_resolved: true
      channel: '#integrationsplattform-monitoring-alerting'
      api_url: 'https://hooks.slack.com/services/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'
      text: 'Greetings from alertmanager'
      title: 'Hello!'
