version: '3.1'

volumes:
  prometheus_data: {}
  grafana_data: {}
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  front-tier:
  back-tier:

version: '3'
services:
  prometheus:
    image: 'prom/prometheus:v2.1.0'
    container_name: prometheus
    ports:
      - '9090:9090'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro'
      - './prometheus/alert.rules:/etc/prometheus/alert.rules'
    depends_on:
      - cadvisor
    networks:
      - backendnet
  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    ports:
      - '8081:8081'
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    networks:
      - backendnet
  alertmanager:
    image: prom/alertmanager
    ports:
      - '9093:9093'
    volumes:
      - './alertmanager/:/etc/alertmanager/'
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    networks:
      - backendnet
  node-exporter:
    image: prom/node-exporter
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/:/rootfs:ro'
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - '9100:9100'
    networks:
      - backendnet
    restart: always
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    volumes:
      - 'grafana_data:/var/lib/grafana'
      - './grafana/provisioning/:/etc/grafana/provisioning/'
    env_file:
      - ./grafana/config.monitoring
    networks:
      - backendnet
    restart: always
  
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
  wordpress:
    image: docker.io/bitnami/wordpress:5
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
